### ISSUE TITLE
Error 500 when i try to generate API token

### ISSUE THREAD

**Issue by djedje72** [anonaddy/docker#31]
### Behaviour
Should be able to generate API Token

#### Steps to reproduce this issue

1. Go to settings page
2. Click on "Generate New Token"
3. Fill the field and click on "Generate Token"

#### Expected behaviour

> When i click on generate api token, i should show the new token

#### Actual behaviour

> When i click on generate api token, i see no error message. I can see a 500 error in network tab.

### Logs

```
2020-10-26 10:45:00,stdout,crond: USER anonaddy pid 1013 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
2020-10-26 10:44:15,stdout,"172.17.0.1 - - [26/Oct/2020:10:44:15 +0000] \"POST /oauth/personal-access-tokens HTTP/1.1\" 500 14484 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:44:10,stdout,"172.17.0.1 - - [26/Oct/2020:10:44:10 +0000] \"GET /site.webmanifest HTTP/1.1\" 200 442 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:44:10,stdout,"172.17.0.1 - - [26/Oct/2020:10:44:10 +0000] \"GET /oauth/personal-access-tokens HTTP/1.1\" 200 33 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:44:10,stdout,"172.17.0.1 - - [26/Oct/2020:10:44:10 +0000] \"GET /settings HTTP/1.1\" 200 15659 \"https://anonaddy.DOMAIN.com/recipients\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:44:02,stdout,Oct 26 10:44:02 mail postfix/smtpd[1011]: disconnect from unknown[172.17.0.1] ehlo=1 auth=0/1 quit=1 commands=2/3
2020-10-26 10:44:02,stdout,Oct 26 10:44:02 mail postfix/smtpd[1011]: connect from unknown[172.17.0.1]
2020-10-26 10:44:00,stdout,crond: USER anonaddy pid 1004 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
2020-10-26 10:43:00,stdout,crond: USER anonaddy pid 997 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
2020-10-26 10:42:00,stdout,crond: USER anonaddy pid 990 cmd php /var/www/anonaddy/artisan schedule:run --no-ansi --no-interaction --quiet
2020-10-26 10:41:59,stdout,"172.17.0.1 - - [26/Oct/2020:10:41:59 +0000] \"POST /oauth/personal-access-tokens HTTP/1.1\" 500 14484 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:41:50,stdout,"172.17.0.1 - - [26/Oct/2020:10:41:50 +0000] \"POST /oauth/personal-access-tokens HTTP/1.1\" 500 14484 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
2020-10-26 10:41:44,stdout,"172.17.0.1 - - [26/Oct/2020:10:41:44 +0000] \"GET /oauth/personal-access-tokens HTTP/1.1\" 200 33 \"https://anonaddy.DOMAIN.com/settings\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36\"
```

**Comment by crazy-max** [comment]
@willbrowningme Are you aware of this issue?

**Comment by willbrowningme** [comment]
Not aware of this issue. Please could you let me know the contents of the `/var/www/anonaddy/storage/logs` file when this error occurs.

**Comment by crazy-max** [comment]
@djedje72 

> Please could you let me know the contents of the /var/www/anonaddy/storage/logs file when this error occurs.

For the Docker image it's located in `/data/storage/logs`

**Comment by djedje72** [comment]
@crazy-max @willbrowningme 

```
[2020-10-26 10:44:15] production.ERROR: Personal access client not found. Please create one. {"userId":"71fc5d26-2e9c-4a09-99f2-e95216ea4356","exception":"[object] (RuntimeException(code: 0): Personal access client not found. Please create one. at /var/www/anonaddy/vendor/laravel/passport/src/ClientRepository.php:122)
[stacktrace]
#0 /var/www/anonaddy/vendor/laravel/passport/src/PersonalAccessTokenFactory.php(72): Laravel\\Passport\\ClientRepository->personalAccessClient()
#1 /var/www/anonaddy/vendor/laravel/passport/src/HasApiTokens.php(67): Laravel\\Passport\\PersonalAccessTokenFactory->make('71fc5d26-2e9c-4...', 'chrome', Array)
#2 /var/www/anonaddy/vendor/laravel/passport/src/Http/Controllers/PersonalAccessTokenController.php(69): App\\Models\\User->createToken('chrome', Array)
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController->store(Object(Illuminate\\Http\\Request))
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController), 'store')
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/anonaddy/app/Http/Middleware/VerifyTwoFactorAuth.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\VerifyTwoFactorAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /var/www/anonaddy/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/anonaddy/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/anonaddy/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 /var/www/anonaddy/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 {main}
"} 
```

**Comment by willbrowningme** [comment]
You need to create a personal access client by running 

```bash
php artisan passport:client --personal
```

Then you need to update your `.env` file as instructed here - https://laravel.com/docs/8.x/passport#creating-a-personal-access-client.

I'll add this to the self-hosting instructions now.

**Comment by djedje72** [comment]
> You need to create a personal access client by running
> 
> ```shell
> php artisan passport:client --personal
> ```
> 
> Then you need to update your `.env` file as instructed here - https://laravel.com/docs/8.x/passport#creating-a-personal-access-client.
> 
> I'll add this to the self-hosting instructions now.
Thank you :)

Where is the .env file for docker install ?

**Comment by djedje72** [comment]
@crazy-max 

Where is the .env file for docker install ?

**Comment by crazy-max** [comment]
Personal access client is actually already created by the Docker image: https://github.com/anonaddy/docker/blob/master/rootfs/etc/cont-init.d/04-svc-main.sh#L10

**Comment by djedje72** [comment]
![image](https://user-images.githubusercontent.com/18309946/97186264-5cdb9500-17a1-11eb-91da-9a8b6a431977.png)

Files are here, but i have the error :(

**Comment by crazy-max** [comment]
@djedje72 Nevermind, personal access client is actually not generated by the docker image. Run the following command to generate one:

```
docker-compose exec anonaddy anonaddy passport:client --personal
```

**Comment by djedje72** [comment]
> @djedje72 Nevermind, personal access client is actually not generated by the docker image. Run the following command to generate one:
> 
> ```
> docker-compose exec anonaddy anonaddy passport:client --personal
> ```

It's ok with that 👍 , should i run this command again if i delete my container ?

**Comment by crazy-max** [comment]
@djedje72 

> It's ok with that 👍 , should i run this command again if i delete my container ?

No you don't need to. I will add a note about personal access client in the README. Thanks for your input.
