### ISSUE TITLE
Swift_TransportException: Expected response code 220 but got code "502"

### ISSUE THREAD

**Issue by vonProteus** [anonaddy/docker#74]
#### Steps to reproduce this issue

1. click resent email address for validation

#### Expected behaviour

enabling accont 

#### Actual behaviour

```
Swift_TransportException:
Expected response code 220 but got code "502", with message "502 5.5.1 Error: command not implemented
"

  at /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459
  at Swift_Transport_AbstractSmtpTransport->assertResponseCode()
     (/var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:344)
  at Swift_Transport_AbstractSmtpTransport->executeCommand()
     (/var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:305)
  at Swift_Transport_EsmtpTransport->executeCommand()
     (/var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:346)
  at Swift_Transport_EsmtpTransport->doHeloCommand()
     (/var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:148)
  at Swift_Transport_AbstractSmtpTransport->start()
     (/var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:65)
  at Swift_Mailer->send()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:521)
  at Illuminate\Mail\Mailer->sendSwiftMessage()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:288)
  at Illuminate\Mail\Mailer->send()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php:65)
  at Illuminate\Notifications\Channels\MailChannel->send()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:148)
  at Illuminate\Notifications\NotificationSender->sendToNotifiable()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:106)
  at Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php:19)
  at Illuminate\Notifications\NotificationSender->withLocale()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:109)
  at Illuminate\Notifications\NotificationSender->sendNow()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php:79)
  at Illuminate\Notifications\NotificationSender->send()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php:39)
  at Illuminate\Notifications\ChannelManager->send()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php:18)
  at App\Models\User->notify()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/MustVerifyEmail.php:38)
  at Illuminate\Foundation\Auth\User->sendEmailVerificationNotification()
     (/var/www/anonaddy/vendor/laravel/ui/auth-backend/VerifiesEmails.php:89)
  at App\Http\Controllers\Auth\VerificationController->resend()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54)
  at Illuminate\Routing\Controller->callAction()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45)
  at Illuminate\Routing\ControllerDispatcher->dispatch()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php:254)
  at Illuminate\Routing\Route->runController()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php:197)
  at Illuminate\Routing\Route->run()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php:695)
  at Illuminate\Routing\Router->Illuminate\Routing\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php:50)
  at Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50)
  at Illuminate\Routing\Middleware\SubstituteBindings->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78)
  at Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:58)
  at Illuminate\Session\Middleware\AuthenticateSession->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:127)
  at Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php:63)
  at Illuminate\Routing\Middleware\ThrottleRequests->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:44)
  at Illuminate\Auth\Middleware\Authenticate->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49)
  at Illuminate\View\Middleware\ShareErrorsFromSession->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121)
  at Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64)
  at Illuminate\Session\Middleware\StartSession->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37)
  at Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67)
  at Illuminate\Cookie\Middleware\EncryptCookies->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103)
  at Illuminate\Pipeline\Pipeline->then()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php:697)
  at Illuminate\Routing\Router->runRouteWithinStack()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php:672)
  at Illuminate\Routing\Router->runRoute()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636)
  at Illuminate\Routing\Router->dispatchToRoute()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625)
  at Illuminate\Routing\Router->dispatch()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:166)
  at Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21)
  at Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31)
  at Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21)
  at Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40)
  at Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27)
  at Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86)
  at Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/fruitcake/laravel-cors/src/HandleCors.php:38)
  at Fruitcake\Cors\HandleCors->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/fideloper/proxy/src/TrustProxies.php:57)
  at Fideloper\Proxy\TrustProxies->handle()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103)
  at Illuminate\Pipeline\Pipeline->then()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:141)
  at Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
     (/var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:110)
  at Illuminate\Foundation\Http\Kernel->handle()
     (/var/www/anonaddy/public/index.php:52) 
```

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.7, build f0df350
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.21.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Raspberry Pi OS 
* System info (type `uname -a`) : Linux kalipso 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```
version: "3.5"

services:
  db:
    image: sagu/mariadb-alpine
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=anonaddy
      - MYSQL_USER=anonaddy
      - MYSQL_PASSWORD=anonaddy
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s


  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s


  anonaddy:
    image: anonaddy/anonaddy:latest
    ports:
      - target: 25
        published: ${PUBLIC25}
        protocol: tcp
    volumes:
      - anonaddy_data:/data
    environment:
      - DB_HOST=db
      - DB_DATABASE=anonaddy
      - DB_USERNAME=anonaddy
      - DB_PASSWORD=anonaddy
      - REDIS_HOST=redis
      
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
      
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=http_x_forwarded_for
      
      - APP_KEY=base64:#####
      - APP_DEBUG=true
      - APP_URL=https://${HOST}
      
      - ANONADDY_RETURN_PATH=bounces@${HOST}
#      - ANONADDY_ADMIN_USERNAME=proteus
      - ANONADDY_ENABLE_REGISTRATION=true
      - ANONADDY_DOMAIN=${HOST}
      - ANONADDY_ALL_DOMAINS=${HOST}
      - ANONADDY_HOSTNAME=${HOST}
      - ANONADDY_DNS_RESOLVER=${DNS_RESOLVER}
      - ANONADDY_SECRET=###
      - ANONADDY_LIMIT=200
      - ANONADDY_BANDWIDTH_LIMIT=104857600
      - ANONADDY_NEW_ALIAS_LIMIT=10
      - ANONADDY_ADDITIONAL_USERNAME_LIMIT=10

      - MAIL_FROM_NAME=AnonAddy
      - MAIL_FROM_ADDRESS=anonaddy@${HOST}

      - POSTFIX_DEBUG=false
      - POSTFIX_SMTPD_TLS=false
      - POSTFIX_SMTP_TLS=false
      
    networks:
      - internal
      - external
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 5s
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:${HOST}"
        traefik.port: 8000
        traefik.docker.network: traefik-net
        traefik.frontend.headers.STSSeconds: 63072000
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"


volumes:
  db_data:
  anonaddy_data:
  redis_data:
  
networks:
  external:
  internal:
    driver: overlay
    internal: true
  traefik-net:
    external: true
### Environment variables
# HOST
# PUBLIC25
# DNS_RESOLVER
```

### Docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 337
  Running: 70
  Paused: 0
  Stopped: 267
 Images: 117
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: ljuxjq2iirndgysesdl5ecpdn
  Is Manager: true
  ClusterID: ojek930vs1gao0y2d2ofiu7ve
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.172.38
  Manager Addresses:
   192.168.172.38:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.17-v8+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.642GiB
 Name: kalipso
 ID: 7EAH:W6Y3:VW4E:VUMI:3DEP:EBDU:RDXP:U3L5:KJA2:D4A5:5T5Z:UA3S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

```
[2021-08-07 15:43:16] production.ERROR: Expected response code 220 but got code "502", with message "502 5.5.1 Error: command not implemented
" {"exception":"[object] (Swift_TransportException(code: 502): Expected response code 220 but got code \"502\", with message \"502 5.5.1 Error: command not implemented
\" at /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459)
[stacktrace]
#0 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(346): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#4 /var/www/anonaddy/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send()
#6 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#7 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(65): Illuminate\\Mail\\Mailer->send()
#8 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send()
#9 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#10 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#11 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(109): Illuminate\\Notifications\\NotificationSender->withLocale()
#12 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#13 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#14 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
#15 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/MustVerifyEmail.php(38): App\\Models\\User->notify()
#16 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Auth/Listeners/SendEmailVerificationNotification.php(19): Illuminate\\Foundation\\Auth\\User->sendEmailVerificationNotification()
#17 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): Illuminate\\Auth\\Listeners\\SendEmailVerificationNotification->handle()
#18 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#19 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch()
#20 /var/www/anonaddy/vendor/laravel/ui/auth-backend/RegistersUsers.php(34): event()
#21 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\RegisterController->register()
#22 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#23 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#24 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#25 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#26 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#27 /var/www/anonaddy/app/Http/Middleware/RedirectIfAuthenticated.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\RedirectIfAuthenticated->handle()
#29 /var/www/anonaddy/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#31 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#33 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#35 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#37 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#39 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#41 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#42 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#44 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#46 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#49 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#50 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#51 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#52 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#53 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#55 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#56 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#58 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#59 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#61 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#63 /var/www/anonaddy/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#65 /var/www/anonaddy/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#67 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#69 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#70 /var/www/anonaddy/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#71 {main}
"} 

```

**Comment by crazy-max** [comment]
Should be fixed with latest release. cc @willbrowningme
