### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by cook1emr** [anonaddy/docker#84]
### UI not accessible

when navigating to http://ip:8000 I receive HTTP ERROR 500

within the container logs I see the below, but am unsure how to solve this
 
```

2021/09/24 16:14:24 [error] 694#694: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. in /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55 
Stack trace: 
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\Encryption\Encrypter->__construct() 
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}() 
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build() 
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve() 
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Illuminate\Foundation\Application->resolve() 
#5...PHP message: PHP Fatal error:  Uncaught RuntimeException: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. in /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55 
Stack trace: 
#0 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\Encryption\Encrypter->__construct() 
#1 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(869): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}() 
#2 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(754): Illuminate\Container\Container->build() 
#3 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\Container\Container->resolve() 
#4 /var/www/anonaddy/vendor/laravel/framework/src/Illuminate/Container/Container.php(692): Il 
192.168.1.98 - - [24/Sep/2021:16:14:24 +0100] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" 

```

**Comment by willbrowningme** [comment]
Please try running `php artisan key:generate` in the app directory to generate a new key.

**Comment by cook1emr** [comment]
Hi, thanks for your response, I have just identified the issue the APP_KEY variable requires a prefix of base64: to work. Please update the docs

**Comment by luckydonald** [comment]
For docker compose with the `anonaddy` service like in the example, that's 
```shell
docker compose run  --entrypoint="php"  anonaddy  artisan key:generate --show
```
